name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK17
      uses: actions/setup-java@main
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Build
      run: |
        make scala-cli
        cp scala-cli /usr/local/bin/
        make
